In [1]:
import numpy as np

In [2]:
# 배열을 생성하면서 값을 초기화 하는 방법: np.zeros(),np.ones()
a = np.zeros(5)
print(a)
b = np.zeros((2,3))
print(b)
print(np.zeros((5,2),dtype='i'))
print(np.zeros(5, dtype='U4'))
print(np.ones((2,3,4),dtype = 'i8'))
print(np.ones_like(b,dtype='f'))
print(np.empty((4,3))) # 배열 메모리안에 이미 값이 들어있음을 보여줌
print(np.array([0,1,-1,0])/np.array([1,0,0,0]))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
['' '' '' '' '']
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[  0.  inf -inf  nan]


C:\Users\shhmu\anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
C:\Users\shhmu\anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


In [3]:
x2 = np.array([-1.0,-2.0])
z1 = np.array([[5.0],[10.0],[15.0]])
x2 + z1

array([[ 4.,  3.],
       [ 9.,  8.],
       [14., 13.]])

In [4]:
# numpy indexing, slicing, iterating
arr = np.arange(10)**2
print(arr)
print(arr[2])
print(arr[3:5]) # 9 ,16
arr[0:6:2] = -arr[0:6:2] # 0, -4(2), -16(4)
print(arr)
print(arr[ : : -1])
for i in arr:
    print(i,end='\t')
print()
arr = np.arange(1,21,1).reshape(4,5)
print(arr)
print(arr[3,4]) # 20
print(arr[0:3,1:]) # 0:3-> 0행부터 2행까지 3은 포함하지 않음
print()
print(arr[1, ]) #1행 출력
print()
print(arr[-1, ]) #마지막 행 출력

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[ 0  4 16]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]
0	1	-4	9	-16	25	36	49	64	81	
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

[ 6  7  8  9 10]

[16 17 18 19 20]


In [6]:
print(arr[ : : -1])
print(arr)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
# numpy 일반 함수
# np.cos(),sin(),tan(),exp()
arr = np.arange(0, 6, 1)
print(arr, np.cos(arr), np.exp(arr))

arr = np.arange(0.01,1,0.05)
print(np.log(arr))

[0 1 2 3 4 5] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]


In [7]:
arr1 = np.array([2,3,4])
arr2 = np.array([1,5,2])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1,arr2))
print(np.sum(arr1))
print(np.random.choice(100,5)) # 0~100사이의 수 중에서 5개 출력
print(np.random.rand(2,3)) # 2행 3열의 random값 리턴
print(np.random.randn(2,3)) # 2행 3열의 random 값 리턴 (표준 정규분포)

# 위치를 반환하는 함수 argmax, argmin
arr = np.array([6,2,3,1,4,5])
print(np.argmax(arr),':',arr[np.argmax(arr)]) #arrgmax:가장큰값 인덱스 반환

arr3 = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]])
print(arr3)
print(np.argmax(arr3, axis=1)) #[0[1[2[3...]]]]<- axis 번호
print(np.argmax(arr3, axis=0)) 

[2 5 4]
[1 3 2]
9
[85 92 51 10 13]
[[0.74699249 0.13227292 0.61624964]
 [0.44000321 0.59766424 0.89063933]]
[[-1.0383697   1.00266702  0.62984806]
 [ 0.63332969 -1.99481195  1.29796739]]
0 : 6
[[0.1 0.8 0.2]
 [0.3 0.2 0.5]
 [0.9 0.5 0.3]]
[1 2 0]
[2 0 1]


In [8]:
# 기술 통계 함수
# count(), mean(), var(), std(), median(), max(), min(), percentile()
arr = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,
               2,5,4,15,-1,4,-7,-24,7,9,-6,-23,-13])
print(len(arr)) # arr의 갯수
print(np.mean(arr)) # 평균
print(np.var(arr)) # 분산
print(np.std(arr)) #표준편차
print(np.max(arr), np.min(arr), np.median(arr)) #최대값, 최소값, 중앙값
print(np.percentile(arr,25)) # 1사분위의 수
print(np.percentile(arr,50)) # 2사분위의 수
print(np.percentile(arr,100)) # 최대 값

26
3.0384615384615383
129.1139053254438
11.362829987527041
23 -24 4.5
-0.75
4.5
23.0


In [9]:
# 난수 발생과 카운탱
np.random.seed(100) #한번 시행하면 계속 시행해도 같은 값
np.random.rand(5)   #np.random.seed(100)없으면 새행할때마다 값이 바뀜

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [10]:
# 데이터 순서를 바꾸는 방법
arr = np.arange(10)
print(arr)
np.random.shuffle(arr) # arr자료의 순서를 바꿈
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[8 4 3 0 1 6 7 9 5 2]


In [11]:
# 샘플링 : choice()
np.random.choice(5,5, replace= False) # shuffle 과 같은 결과
#               앞의 5 -> range(5)
np.random.choice(10,3,replace = False) #10개중 3개만 선택 
# replace = False -> 중복선택 불가
np.random.choice(5,10) # 5개 숫자에서 10개 추출:중복 허용
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0]) # 선택확률을 다르게, 데이터 수만큼
#                        [0.0,1,2.0,3.0,4]       확률 넣고 p의 합은 1이 되게


array([3, 3, 2, 3, 3, 2, 3, 3, 3, 0])

In [12]:
# randint() 정수 난수 발생 numpy.random.randint(low, high=None, size=None)
# =None 은 생략 가능
# np.random.seed(0) # -> 항상 같은 데이터만 가져오게 함
np.random.randint(10, size=10) #<- replace = True (기본)
np.random.randint(10,20, size=10) #20은 포함 안함
np.random.randint(10,20, size=(3,5)) #3행 5열의 array 반환

array([[16, 13, 19, 10, 14],
       [14, 15, 17, 16, 16],
       [12, 14, 12, 17, 11]])

In [22]:
x = np.arange(20) +1
n_list = []
print(x [x % 3 == 0])
print(x [x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 == 1)])# 3의 배수이면서 4로 나누면 나머지 1인수

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
